### PR TITLE
Add onActivate function

### PR DESCRIPTION
**Pull request by chdanielmueller**
I did add the functionality for an onActivate function.
It will be triggered when a menuItem gets activated.

I also did change the isActive comparison to string, because isActive was always false if I had more than one activeClass (like the sample)

### CODE REVIEW

**Review by sidsbrmnn — APPROVED** [review]
This looks good. Thanks for contributing mate

**Comment by chdanielmueller** [comment]
Hi @sidsbrmnn 
Do you still plan to publish these changes?
Thanks for your feedback

**Comment by sidsbrmnn** [comment]
> Hi @sidsbrmnn Do you still plan to publish these changes? Thanks for your feedback

I've renamed the callback as `onActive` for semantic reasons and is now available in the [current release](https://github.com/sidsbrmnn/scrollspy/releases/tag/v1.1.0)

**Comment by chdanielmueller** [comment]
Thanks for the release.
I found an error in the docs regarding onActive which I fixed.
Please see #14

**Pull request merged**
